
<template>
  <section id="landing-page">
    <h2>THE UNDISPUTABLE GUIDE TO THE GREATEST ALBUMS OF ALL TIME</h2>
    <RouterLink to="/albums">VIEW ALBUMS</RouterLink>
  </section>
</template>
<style>
#landing-page{
  text-align: center;
  height:250px;
  margin: auto 0;
  background-color:aquamarine;
  color:#8e8e8e;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
}
</style>